### ISSUE TITLE
[BUG/echo-server] livenessProbe fails

### ISSUE THREAD

**Issue by masterkain** [Ealenn/charts#25]
hello,
I'm deploying via this HelmRelease:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  releaseName: echo-server
  chart:
    repository: https://ealenn.github.io/charts
    name: echo-server
    version: 0.2.0
  values:
    ingress:
      enabled: true
      hosts:
        - host: echo.my.domain
          paths:
            - /
      tls:
        - secretName: echo-server-tls
          hosts:
            - echo.my.domain
```

however:

```
│Events:
│  Type     Reason     Age                     From               Message
│  ----     ------     ----                    ----               -------
│  Normal   Scheduled  <unknown>               default-scheduler  Successfully assigned echo-server/echo-server-656d9c598b-qzbfh to node-1
│  Normal   Pulling    7m48s (x4 over 8m52s)   kubelet, node-1    Pulling image "ealen/echo-server:0.3.0"
│  Normal   Pulled     7m48s (x4 over 8m50s)   kubelet, node-1    Successfully pulled image "ealen/echo-server:0.3.0"
│  Normal   Created    7m48s (x4 over 8m50s)   kubelet, node-1    Created container echo-server
│  Normal   Started    7m48s (x4 over 8m49s)   kubelet, node-1    Started container echo-server
│  Warning  Unhealthy  7m45s (x3 over 8m45s)   kubelet, node-1    Liveness probe failed: Get http://10.2.0.41:80/ping: dial tcp 10.2.0.41:80: connect: connection refused
│  Normal   Killing    7m45s                   kubelet, node-1    Container echo-server failed liveness probe, will be restarted
│  Warning  BackOff    3m47s (x24 over 8m35s)  kubelet, node-1    Back-off restarting failed container
```

describing the pod this is the printed Liveness:

```
Liveness:  http-get http://:http/ping delay=0s timeout=1s period=10s #success=1 #failure=3
```

is the tls block written correctly? the pod gets killed immediately and with no logs so I can't really tell what's going on inside it

**Comment by Ealenn** [comment]
Hi ! 

I think your pod is too long to respond "`#success=1 #failure=3`"
Hum... I can add something to customize the liveness probe

https://github.com/Ealenn/charts/blob/13f156012ba79ee8a96121fd4f0664834a1d954e/charts/echo-server/templates/deployment.yaml

I will also test your configuration tomorrow ;)

PS: 
TLS configuration is good
<details> 
  <summary>helm template ealenn/echo-server -f masterkain.yml</summary>
<div class="highlight highlight-source-yaml"><pre>
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-echo-server
  labels:
    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.2.0
spec:
  tls:
    - hosts:
        - "echo.my.domain"
      secretName: echo-server-tls
  rules:
    - host: "echo.my.domain"
      http:
        paths:
          - path: /
            backend:
              serviceName: RELEASE-NAME-echo-server
              servicePort: 80
</pre></div>
</details>
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

**Comment by Ealenn** [comment]
Try with this : 

```
spec:
...
  values:
...
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
```

Or change chart version with : `0.2.1`

```yaml
...
spec:
  releaseName: echo-server
  chart:
    repository: https://ealenn.github.io/charts
    name: echo-server
    version: 0.2.1
  values:
...
```
