### ISSUE TITLE
[BUG/ECHO-SERVER] Invalid values in liveness probe

### ISSUE THREAD

**Issue by Ealenn** [Ealenn/charts#27]
**Describe the bug**
Invalide `Values` in `livenessProbe`

Up from @masterkain #26 #25 

**In  charts/echo-server/templates/deployment.yaml**
```yaml
    httpGet:
        path: /ping
        port: http
    initialDelaySeconds: {{ .Values.initialDelaySeconds }}
    periodSeconds: {{ .Values.periodSeconds }}
    timeoutSeconds: {{ .Values.timeoutSeconds }}
    failureThreshold: {{ .Values.failureThreshold }}
    successThreshold: {{ .Values.successThreshold }}
```

**Expected behavior**
```yaml
    httpGet:
        path: {{ .Values.livenessProbe.httpGet.path }}
        httpHeaders: {{ .Values.livenessProbe.httpGet.httpHeaders }}
        port: http
    httpHeaders: {{ .Values.livenessProbe.httpHeaders }}
    initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
    periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
    timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
    failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
    successThreshold: {{ .Values.livenessProbe.successThreshold }}
```
